### ISSUE TITLE
implovement

### ISSUE THREAD

**Issue by aTadatoshiTokutake** [ttokutake/php-utils#2]
* `[]` => `array()` for compatiblity of any PHP version excluding test file.
* modify array argument to reference for avoiding copy.
`function hoge(array $array) ` => `function hoge(array &$array)`
* following above, don't use `array_shift()` and `array_pop()`
* `array_map(function ($a) { return count($a); }, $array)` => `array_map('count', $array)`

**Comment by ttokutake** [comment]
1. https://github.com/ttokutake/php-utils/commit/408b5d461d17d98011a37fca2b9afb9ced3c614c
2. https://github.com/ttokutake/php-utils/commit/5f7927e8625731be654ccbcdd033d1f70e52d28f
3. same [2].
4. https://github.com/ttokutake/php-utils/commit/e3ac8c4bc29206f167961f9d00b98e5d173764e0

About [2, 3], a side effect happen slightly.
